services:
  db:
    image: postgres
    restart: always
    ports:
      - "8081:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
